apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: bootcamp-cluster
  region: eu-west-3
  version: "1.28"

iam:
  withOIDC: true

managedNodeGroups:
  - name: bootcamp-nodes
    instanceType: t2.small
    desiredCapacity: 3
    minSize: 1
    maxSize: 4
    ssh:
      allow: true
      publicKeyPath: "../bootcamp_key.pub"
