apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo
      service: monolith
  template:
    metadata:
      labels:
        app: todo
        service: monolith
    spec:
      containers:
      - name: todo-app
        image: antonio/lc-todo-app:v1
        imagePullPolicy: Never
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 100m
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: todo-app-config
